config/routes.rb
Eerlijkepolitiek::Application.routes.draw do
  resources :trophies, only: [:index, :show]

  root to: 'dashboard#index'

  get 'login' => 'authentications#index'
  delete 'logout' => 'sessions#destroy'
  get 'trophies' => 'trophies#index'
  match '/auth/:provider/callback', to: 'sessions#create'
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user

  def self.find_or_create_by_auth_hash(auth_hash)
    auth = find_or_create_by_provider_and_uid( auth_hash['provider'], auth_hash['uid'])
    auth.create_user_by_auth_hash_extras(auth_hash['extra']['raw_info']) unless auth.user
    auth
  end

  def create_user_by_auth_hash_extras(extras)
    Rails.logger.debug extras.inspect
    create_user({
      first_name: extras['first_name'],
      last_name: extras['last_name'],
      email: extras['email']
    })
  end
end

app/models/political_party.rb
class PoliticalParty < ActiveRecord::Base
  extend VoteTrophies

  attr_accessible :name
  cattr_reader :parlis_key
  has_many :votes, primary_key: :parlis_id, foreign_key: :SID_ActorFractie

  VOTED_GOLD = 160
  VOTED_POSITIVE_GOLD = 140
  VOTED_NEGATIVE_GOLD = 140

  @@parlis_key = :SID_ActorFractie

end

app/models/politician.rb
class Politician < ActiveRecord::Base
  extend VoteTrophies

  attr_accessible :name
  cattr_reader :parlis_key
  has_many :parties, through: :politician_parties
  has_many :politician_parties
  has_many :votes, primary_key: :parlis_id, foreign_key: :SID_ActorLid

  VOTED_GOLD = 60
  VOTED_POSITIVE_GOLD = 40
  VOTED_NEGATIVE_GOLD = 40
  @@parlis_key = :SID_ActorLid



  def self.game_changer
    self.joins(:parties).
      group('politician_parties.politician_id').
      having("count(party_id) > 1")
  end


end

app/models/politician_party.rb
class PoliticianParty < ActiveRecord::Base
  belongs_to :politician
  belongs_to :party, class_name: 'PoliticalParty'
end

app/models/trophy.rb
class Trophy
  TROPHIES = {
    voted_gold: {
      personal_description: I18n.t(:description, scope: 'voted_gold', amount: Politician::VOTED_GOLD),
      party_description: I18n.t(:description, scope: 'voted_gold', amount: PoliticalParty::VOTED_GOLD)
    },
    voted_positive_gold: {
      personal_description: I18n.t(:description, scope: 'voted_positive_gold', amount: Politician::VOTED_POSITIVE_GOLD),
      party_description: I18n.t(:description, scope: 'voted_positive_gold', amount: PoliticalParty::VOTED_POSITIVE_GOLD)
    },
    voted_negative_gold: {
      personal_description: I18n.t(:description, scope: 'voted_negative_gold', amount: Politician::VOTED_NEGATIVE_GOLD), 
      party_description: I18n.t(:description, scope: 'voted_negative_gold', amount: PoliticalParty::VOTED_NEGATIVE_GOLD)
    },
    game_changer: {
      personal_description: I18n.t(:description, scope: 'game_changer', amount: 1),
    }
  }
  attr_accessor :key, :personal_description, :party_description, :title

  def initialize key
    self.key = key
    self.personal_description = TROPHIES[key][:personal_description]
    self.party_description = TROPHIES[key][:party_description]
    self.title = I18n.t :title, scope: key
  end

  def self.all
    @trophies ||= TROPHIES.map do |k, v|
      Trophy.new k
    end
  end

  def partial_path obj
    'trophy'
  end

  def winners
    Politician.send self.key
  end

  def party_winners
    PoliticalParty.send self.key
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email

  has_many :authorizations
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  set_table_name 'Stemmingen'
end

app/models/vote_trophies.rb
module VoteTrophies

  def voted_gold
    self.joins(:votes).
      group(self.parlis_key).
      having("count(Stemmingen.id) > #{self::VOTED_GOLD}")
  end

  def voted_positive_gold
    self.joins(:votes).
      where('Stemmingen.Soort = ?', "Voor").
      group(self.parlis_key).
      having("count(Stemmingen.id) > #{self::VOTED_POSITIVE_GOLD}")
  end

  def voted_negative_gold
    self.joins(:votes).
      where('Stemmingen.Soort = ?', "Tegen").
      group(:SID_ActorLid).
      having("count(Stemmingen.id) > #{self::VOTED_NEGATIVE_GOLD}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def user_authenticated?
    !current_user.nil?
  end
  helper_method :user_authenticated?

  def current_user
    @current_user ||= session[:current_user_id] && User.find_by_id(session[:current_user_id])
  end
  helper_method :current_user

  def current_user=(user)
    session[:current_user_id] = user ? user.id : nil
    @current_user = user
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @authorization = Authorization.find_or_create_by_auth_hash(auth_hash)
    self.current_user = @authorization.user
    redirect_to root_path
  end

  def destroy
    self.current_user = nil
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  def index
  end

  def show
    @trophy = Trophy.new params[:id].to_sym
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trophies_helper.rb
module TrophiesHelper
end

app/views/authentications/index.html.haml
.providers
  %a.facebook{ href: '/auth/facebook' } Facebook
  %a.twitter{ href: '/auth/twitter' } Twitter

app/views/layouts/application.html.haml
!!!
%html(lang='nl')
  %head
    %meta(charset='utf-8')
    %title Eerlijke Politiek
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          = link_to 'Eerlijke Politiek', root_path, class: 'brand'
          .nav-collapse.collapse
            - if user_authenticated?
              %ul.nav.pull-right
                %li.navbar-text.authenticated
                  .user-name
                    Ingelogged als
                    = current_user.first_name
                %li= link_to 'Uitloggen', logout_path, class: 'logout', method: :delete
            - else
              %ul.nav.pull-right
                %li= link_to 'Inloggen', login_path, class: 'js-login'\
            %ul.nav
              %li= link_to 'Dashboard', root_path
              %li= link_to 'Trophies', trophies_path

    .container-fluid
      .row-fluid
        .span12
          = yield

app/views/trophies/_trophy.html.haml
%li.trophy.well
  .trophy-data
    = link_to trophy_path(trophy.key) do
      %i.img-polaroid.icon-trophy
    %h4= link_to trophy.title, trophy_path(trophy.key)
  - if trophy.personal_description
    - winners = trophy.winners.all
    .winners-block
      %p 
        = winners.count
        = t 'person', count: winners.count
        who #{trophy.personal_description}
      %ul.politician-winners.winners
        - winners[0..25].each do |winner|
          %li.winner
            %i.img-polaroid.icon-user(title="#{winner.name}")
        - if winners.size > 25
          %li.more-winners
            = link_to '...', trophy_path(trophy.key)
  - if trophy.party_description
    - winners = trophy.party_winners.all
    .winners-block
      %p 
        = winners.count
        = t 'party', count: winners.count
        who #{trophy.party_description}
      %ul.party-winners.winners
        - winners[0..25].each do |winner|
          %li.winner
            %i.img-polaroid.icon-group(title="#{winner.name}")
        - if winners.size > 25
          %li.more-winners
            = link_to '...', trophy_path(trophy.key)

app/views/trophies/index.html.haml
%ul.trophies
  = render partial: 'trophy', collection: Trophy.all

app/views/trophies/show.html.haml
.hero-unit
  %h1= @trophy.title